package com.example.currencyformatapp

class Price(locale: String, currencyCode: String, price: String) {
    var locale = locale
    var currencyCode = currencyCode
    var price = price

    val currencySymbols = mapOf(
            "-" to "-",
            "AED" to "د.إ",
            "AFN" to "؋",
            "ALL" to "Lek",
            "AMD" to "դր.",
            "ANG" to "ƒ",
            "AOA" to "Kz",
            "ARS" to "\$",
            "AUD" to "$",
            "AWG" to "ƒ",
            "AZN" to "m",
            "BAM" to "КМ",
            "BBD" to "\$",
            "BDT" to "৳",
            "BGN" to "лв",
            "BHD" to ".د.ب",
            "BIF" to "Fr",
            "BMD" to "\$",
            "BND" to "$",
            "BOB" to "Bs.",
            "BRL" to "R$",
            "BSD" to "\$",
            "BTN" to "Nu.",
            "BWP" to "P",
            "BYR" to "Br",
            "BZD" to "\$",
            "CAD" to "\$",
            "CDF" to "Fr",
            "CHF" to "Fr",
            "CLP" to "\$",
            "CNY" to "¥",
            "COP" to "\$",
            "CRC" to "₡",
            "CUC" to "\$",
            "CUP" to "\$",
            "CVE" to "\$",
            "CZK" to "Kč",
            "DJF" to "Fr",
            "DKK" to "kr",
            "DOP" to "\$",
            "DZD" to "د.ج",
            "EGP" to "ج.م",
            "ERN" to "Nfk",
            "ETB" to "Br",
            "EUR" to "€",
            "FJD" to "\$",
            "FKP" to "£",
            "GBP" to "£",
            "GEL" to "ლ",
            "GHS" to "₵",
            "GIP" to "£",
            "GMD" to "D",
            "GNF" to "Fr",
            "GTQ" to "Q",
            "GYD" to "\$",
            "HKD" to "\$",
            "HNL" to "L",
            "HRK" to "kn",
            "HTG" to "G",
            "HUF" to "Ft",
            "IDR" to "Rp",
            "ILS" to "₪",
            "INR" to "₹",
            "IQD" to "ع.د",
            "IRR" to "﷼",
            "ISK" to "kr",
            "JMD" to "\$",
            "JOD" to "د.ا",
            "JPY" to "¥",
            "KES" to "Sh",
            "KGS" to "лв",
            "KHR" to "៛",
            "KMF" to "Fr",
            "KPW" to "₩",
            "KRW" to "₩",
            "KWD" to "د.ك",
            "KYD" to "\$",
            "KZT" to "₸",
            "LAK" to "₭",
            "LBP" to "ل.ل",
            "LKR" to "Rs",
            "LRD" to "\$",
            "LSL" to "L",
            "LTL" to "Lt",
            "LYD" to "ل.د",
            "MAD" to "د.م.",
            "MDL" to "L",
            "MGA" to "Ar",
            "MKD" to "ден",
            "MMK" to "Ks",
            "MNT" to "₮",
            "MOP" to "P",
            "MRO" to "UM",
            "MUR" to "₨",
            "MVR" to ".ރ",
            "MWK" to "MK",
            "MXN" to "\$",
            "MYR" to "RM",
            "MZN" to "MT",
            "NAD" to "$",
            "NGN" to "₦",
            "NIO" to "C$",
            "NOK" to "kr",
            "NPR" to "₨",
            "NZD" to "\$",
            "OMR" to "ر.ع.",
            "PAB" to "B/.",
            "PEN" to "S/.",
            "PGK" to "K",
            "PHP" to "₱",
            "PKR" to "₨",
            "PLN" to "zł",
            "PYG" to "₲",
            "QAR" to "ر.ق",
            "RON" to "L",
            "RSD" to "дин.",
            "RUB" to "руб.",
            "RWF" to "Fr",
            "SAR" to "ر.س",
            "SBD" to "\$",
            "SCR" to "₨",
            "SDG" to "£",
            "SEK" to "kr",
            "SGD" to "\$",
            "SHP" to "£",
            "SLL" to "Le",
            "SOS" to "Sh",
            "SRD" to "\$",
            "SSP" to "£",
            "STD" to "Db",
            "SYP" to "ل.س",
            "SZL" to "L",
            "THB" to "฿",
            "TJS" to "ЅМ",
            "TMT" to "m",
            "TND" to "د.ت",
            "TOP" to "T$",
            "TRY" to "NULL",
            "TTD" to "\$",
            "TWD" to "\$",
            "TZS" to "Sh",
            "UAH" to "₴",
            "UGX" to "Sh",
            "USD" to "\$",
            "UYU" to "\$",
            "UZS" to "лв",
            "VEF" to "Bs F",
            "VND" to "₫",
            "VUV" to "Vt",
            "WST" to "T",
            "XAF" to "Fr",
            "XCD" to "\$",
            "XOF" to "Fr",
            "XPF" to "Fr",
            "YER" to "﷼",
            "ZAR" to "R",
            "ZMW" to "ZK"
    )

    val localesMap = mapOf(
            "" to Formats.SYMBOL_BLANK_COMA_DOT,
            "nds" to Formats.SYMBOL_BLANK_COMA_DOT,
            "bo_CN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "qu_EC" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ta_SG" to Formats.SYMBOL_BLANK_COMA_DOT,
            "vo" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ha_NG" to Formats.SYMBOL_BLANK_COMA_DOT,
            "lkt_US" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ji_001" to Formats.SYMBOL_BLANK_COMA_DOT,
            "vo_001" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ji" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ar_EH" to Formats.SYMBOL_BLANK_COMA_DOT,
            "nds_DE" to Formats.SYMBOL_BLANK_COMA_DOT,
            "mn" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ta_MY" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ta" to Formats.SYMBOL_BLANK_COMA_DOT,
            "lag" to Formats.SYMBOL_BLANK_COMA_DOT,
            "bo" to Formats.SYMBOL_BLANK_COMA_DOT,
            "to" to Formats.SYMBOL_BLANK_COMA_DOT,
            "qu" to Formats.SYMBOL_BLANK_COMA_DOT,
            "pa_IN_#Guru" to Formats.SYMBOL_BLANK_COMA_DOT,
            "brx" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ha" to Formats.SYMBOL_BLANK_COMA_DOT,
            "bo_IN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "cu_RU" to Formats.SYMBOL_BLANK_COMA_DOT,
            "brx_IN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "mg" to Formats.SYMBOL_BLANK_COMA_DOT,
            "nds_NL" to Formats.SYMBOL_BLANK_COMA_DOT,
            "mgo" to Formats.SYMBOL_BLANK_COMA_DOT,
            "to_TO" to Formats.SYMBOL_BLANK_COMA_DOT,
            "pa__#Guru" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ii_CN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "pa" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ha_GH" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ta_LK" to Formats.SYMBOL_BLANK_COMA_DOT,
            "qu_PE" to Formats.SYMBOL_BLANK_COMA_DOT,
            "kok_IN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "prg_001" to Formats.SYMBOL_BLANK_COMA_DOT,
            "prg" to Formats.SYMBOL_BLANK_COMA_DOT,
            "lag_TZ" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ur" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ur_PK" to Formats.SYMBOL_BLANK_COMA_DOT,
            "mn_MN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ii" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ta_IN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "lkt" to Formats.SYMBOL_BLANK_COMA_DOT,
            "mg_MG" to Formats.SYMBOL_BLANK_COMA_DOT,
            "cu" to Formats.SYMBOL_BLANK_COMA_DOT,
            "en_IN" to Formats.SYMBOL_BLANK_COMA_DOT,
            "kok" to Formats.SYMBOL_BLANK_COMA_DOT,
            "zu" to Formats.SYMBOL_COMA_DOT,
            "am_ET" to Formats.SYMBOL_COMA_DOT,
            "ti_ET" to Formats.SYMBOL_COMA_DOT,
            "en_NU" to Formats.SYMBOL_COMA_DOT,
            "zh_SG_#Hans" to Formats.SYMBOL_COMA_DOT,
            "en_MS" to Formats.SYMBOL_COMA_DOT,
            "en_GG" to Formats.SYMBOL_COMA_DOT,
            "en_JM" to Formats.SYMBOL_COMA_DOT,
            "mer" to Formats.SYMBOL_COMA_DOT,
            "en_ZM" to Formats.SYMBOL_COMA_DOT,
            "ml" to Formats.SYMBOL_COMA_DOT,
            "en_MT" to Formats.SYMBOL_COMA_DOT,
            "en_LR" to Formats.SYMBOL_COMA_DOT,
            "en_GH" to Formats.SYMBOL_COMA_DOT,
            "en_IL" to Formats.SYMBOL_COMA_DOT,
            "vai_LR_#Latn" to Formats.SYMBOL_COMA_DOT,
            "yo_NG" to Formats.SYMBOL_COMA_DOT,
            "en_PW" to Formats.SYMBOL_COMA_DOT,
            "fil_PH" to Formats.SYMBOL_COMA_DOT,
            "en_VC" to Formats.SYMBOL_COMA_DOT,
            "es_US" to Formats.SYMBOL_COMA_DOT,
            "en_KN" to Formats.SYMBOL_COMA_DOT,
            "ebu" to Formats.SYMBOL_COMA_DOT,
            "zh__#Hans" to Formats.SYMBOL_COMA_DOT,
            "es_GT" to Formats.SYMBOL_COMA_DOT,
            "so_KE" to Formats.SYMBOL_COMA_DOT,
            "kam_KE" to Formats.SYMBOL_COMA_DOT,
            "teo" to Formats.SYMBOL_COMA_DOT,
            "en_MO" to Formats.SYMBOL_COMA_DOT,
            "en_BZ" to Formats.SYMBOL_COMA_DOT,
            "es_DO" to Formats.SYMBOL_COMA_DOT,
            "en_NR" to Formats.SYMBOL_COMA_DOT,
            "nd" to Formats.SYMBOL_COMA_DOT,
            "en_MP" to Formats.SYMBOL_COMA_DOT,
            "en_GD" to Formats.SYMBOL_COMA_DOT,
            "en_BW" to Formats.SYMBOL_COMA_DOT,
            "en_AU" to Formats.SYMBOL_COMA_DOT,
            "en_CY" to Formats.SYMBOL_COMA_DOT,
            "kde_TZ" to Formats.SYMBOL_COMA_DOT,
            "ti_ER" to Formats.SYMBOL_COMA_DOT,
            "nus_SS" to Formats.SYMBOL_COMA_DOT,
            "nd_ZW" to Formats.SYMBOL_COMA_DOT,
            "en_IE" to Formats.SYMBOL_COMA_DOT,
            "zh_SG" to Formats.SYMBOL_COMA_DOT,
            "en_KI" to Formats.SYMBOL_COMA_DOT,
            "om_ET" to Formats.SYMBOL_COMA_DOT,
            "or_IN" to Formats.SYMBOL_COMA_DOT,
            "en_SZ" to Formats.SYMBOL_COMA_DOT,
            "zh" to Formats.SYMBOL_COMA_DOT,
            "es_PE" to Formats.SYMBOL_COMA_DOT,
            "saq" to Formats.SYMBOL_COMA_DOT,
            "en_GB" to Formats.SYMBOL_COMA_DOT,
            "zh_HK_#Hant" to Formats.SYMBOL_COMA_DOT,
            "es_PA" to Formats.SYMBOL_COMA_DOT,
            "om_KE" to Formats.SYMBOL_COMA_DOT,
            "en_AS" to Formats.SYMBOL_COMA_DOT,
            "zh_TW" to Formats.SYMBOL_COMA_DOT,
            "kln" to Formats.SYMBOL_COMA_DOT,
            "kw" to Formats.SYMBOL_COMA_DOT,
            "vai__#Latn" to Formats.SYMBOL_COMA_DOT,
            "en_JE" to Formats.SYMBOL_COMA_DOT,
            "en_CX" to Formats.SYMBOL_COMA_DOT,
            "luy_KE" to Formats.SYMBOL_COMA_DOT,
            "yue_CN_#Hans" to Formats.SYMBOL_COMA_DOT,
            "kn_IN" to Formats.SYMBOL_COMA_DOT,
            "en_SX" to Formats.SYMBOL_COMA_DOT,
            "ga" to Formats.SYMBOL_COMA_DOT,
            "en_TZ" to Formats.SYMBOL_COMA_DOT,
            "en_PR" to Formats.SYMBOL_COMA_DOT,
            "ko_KP" to Formats.SYMBOL_COMA_DOT,
            "sn" to Formats.SYMBOL_COMA_DOT,
            "rof" to Formats.SYMBOL_COMA_DOT,
            "en_BS" to Formats.SYMBOL_COMA_DOT,
            "gv" to Formats.SYMBOL_COMA_DOT,
            "gd_GB" to Formats.SYMBOL_COMA_DOT,
            "en_KE" to Formats.SYMBOL_COMA_DOT,
            "guz" to Formats.SYMBOL_COMA_DOT,
            "ja" to Formats.SYMBOL_COMA_DOT,
            "or" to Formats.SYMBOL_COMA_DOT,
            "te" to Formats.SYMBOL_COMA_DOT,
            "es_MX" to Formats.SYMBOL_COMA_DOT,
            "es_HN" to Formats.SYMBOL_COMA_DOT,
            "en_SS" to Formats.SYMBOL_COMA_DOT,
            "sw" to Formats.SYMBOL_COMA_DOT,
            "en_MG" to Formats.SYMBOL_COMA_DOT,
            "vai__#Vaii" to Formats.SYMBOL_COMA_DOT,
            "kn" to Formats.SYMBOL_COMA_DOT,
            "gu" to Formats.SYMBOL_COMA_DOT,
            "vun_TZ" to Formats.SYMBOL_COMA_DOT,
            "jmc_TZ" to Formats.SYMBOL_COMA_DOT,
            "en_TV" to Formats.SYMBOL_COMA_DOT,
            "en_PN" to Formats.SYMBOL_COMA_DOT,
            "en_MH" to Formats.SYMBOL_COMA_DOT,
            "zh__#Hant" to Formats.SYMBOL_COMA_DOT,
            "zh_HK_#Hans" to Formats.SYMBOL_COMA_DOT,
            "en_GY" to Formats.SYMBOL_COMA_DOT,
            "mas" to Formats.SYMBOL_COMA_DOT,
            "am" to Formats.SYMBOL_COMA_DOT,
            "en_NG" to Formats.SYMBOL_COMA_DOT,
            "ki_KE" to Formats.SYMBOL_COMA_DOT,
            "en_PK" to Formats.SYMBOL_COMA_DOT,
            "zh_CN" to Formats.SYMBOL_COMA_DOT,
            "en_LC" to Formats.SYMBOL_COMA_DOT,
            "iw" to Formats.SYMBOL_COMA_DOT,
            "gv_IM" to Formats.SYMBOL_COMA_DOT,
            "en_TT" to Formats.SYMBOL_COMA_DOT,
            "dav" to Formats.SYMBOL_COMA_DOT,
            "te_IN" to Formats.SYMBOL_COMA_DOT,
            "mt_MT" to Formats.SYMBOL_COMA_DOT,
            "mer_KE" to Formats.SYMBOL_COMA_DOT,
            "ko" to Formats.SYMBOL_COMA_DOT,
            "en_BM" to Formats.SYMBOL_COMA_DOT,
            "ak" to Formats.SYMBOL_COMA_DOT,
            "kde" to Formats.SYMBOL_COMA_DOT,
            "en_US" to Formats.SYMBOL_COMA_DOT,
            "gu_IN" to Formats.SYMBOL_COMA_DOT,
            "yue__#Hans" to Formats.SYMBOL_COMA_DOT,
            "en_NF" to Formats.SYMBOL_COMA_DOT,
            "bm" to Formats.SYMBOL_COMA_DOT,
            "en_GU" to Formats.SYMBOL_COMA_DOT,
            "en_AI" to Formats.SYMBOL_COMA_DOT,
            "cgg" to Formats.SYMBOL_COMA_DOT,
            "ms_MY" to Formats.SYMBOL_COMA_DOT,
            "en_TO" to Formats.SYMBOL_COMA_DOT,
            "cy" to Formats.SYMBOL_COMA_DOT,
            "en_PG" to Formats.SYMBOL_COMA_DOT,
            "en_ER" to Formats.SYMBOL_COMA_DOT,
            "zu_ZA" to Formats.SYMBOL_COMA_DOT,
            "en_PH" to Formats.SYMBOL_COMA_DOT,
            "zh_MO_#Hans" to Formats.SYMBOL_COMA_DOT,
            "en_DM" to Formats.SYMBOL_COMA_DOT,
            "en_CK" to Formats.SYMBOL_COMA_DOT,
            "ga_IE" to Formats.SYMBOL_COMA_DOT,
            "en_AG" to Formats.SYMBOL_COMA_DOT,
            "en_WS" to Formats.SYMBOL_COMA_DOT,
            "ebu_KE" to Formats.SYMBOL_COMA_DOT,
            "bem_ZM" to Formats.SYMBOL_COMA_DOT,
            "so" to Formats.SYMBOL_COMA_DOT,
            "en_NA" to Formats.SYMBOL_COMA_DOT,
            "ms" to Formats.SYMBOL_COMA_DOT,
            "nus" to Formats.SYMBOL_COMA_DOT,
            "sn_ZW" to Formats.SYMBOL_COMA_DOT,
            "iw_IL" to Formats.SYMBOL_COMA_DOT,
            "ug" to Formats.SYMBOL_COMA_DOT,
            "hi" to Formats.SYMBOL_COMA_DOT,
            "en_SL" to Formats.SYMBOL_COMA_DOT,
            "teo_KE" to Formats.SYMBOL_COMA_DOT,
            "zh_MO_#Hant" to Formats.SYMBOL_COMA_DOT,
            "en_SH" to Formats.SYMBOL_COMA_DOT,
            "vai" to Formats.SYMBOL_COMA_DOT,
            "haw_US" to Formats.SYMBOL_COMA_DOT,
            "en_KY" to Formats.SYMBOL_COMA_DOT,
            "mt" to Formats.SYMBOL_COMA_DOT,
            "si_LK" to Formats.SYMBOL_COMA_DOT,
            "kam" to Formats.SYMBOL_COMA_DOT,
            "en_ZW" to Formats.SYMBOL_COMA_DOT,
            "ee" to Formats.SYMBOL_COMA_DOT,
            "en_UM" to Formats.SYMBOL_COMA_DOT,
            "en_TK" to Formats.SYMBOL_COMA_DOT,
            "vai_LR_#Vaii" to Formats.SYMBOL_COMA_DOT,
            "saq_KE" to Formats.SYMBOL_COMA_DOT,
            "chr" to Formats.SYMBOL_COMA_DOT,
            "ms_SG" to Formats.SYMBOL_COMA_DOT,
            "yue__#Hant" to Formats.SYMBOL_COMA_DOT,
            "es_BZ" to Formats.SYMBOL_COMA_DOT,
            "luy" to Formats.SYMBOL_COMA_DOT,
            "rof_TZ" to Formats.SYMBOL_COMA_DOT,
            "en_FM" to Formats.SYMBOL_COMA_DOT,
            "es_PR" to Formats.SYMBOL_COMA_DOT,
            "naq" to Formats.SYMBOL_COMA_DOT,
            "en_SG" to Formats.SYMBOL_COMA_DOT,
            "ee_GH" to Formats.SYMBOL_COMA_DOT,
            "kln_KE" to Formats.SYMBOL_COMA_DOT,
            "om" to Formats.SYMBOL_COMA_DOT,
            "hi_IN" to Formats.SYMBOL_COMA_DOT,
            "en_SD" to Formats.SYMBOL_COMA_DOT,
            "en_MY" to Formats.SYMBOL_COMA_DOT,
            "es_SV" to Formats.SYMBOL_COMA_DOT,
            "ml_IN" to Formats.SYMBOL_COMA_DOT,
            "fil" to Formats.SYMBOL_COMA_DOT,
            "en_FK" to Formats.SYMBOL_COMA_DOT,
            "yue_HK_#Hant" to Formats.SYMBOL_COMA_DOT,
            "en_GM" to Formats.SYMBOL_COMA_DOT,
            "en_DG" to Formats.SYMBOL_COMA_DOT,
            "ak_GH" to Formats.SYMBOL_COMA_DOT,
            "zh_CN_#Hans" to Formats.SYMBOL_COMA_DOT,
            "es_419" to Formats.SYMBOL_COMA_DOT,
            "si" to Formats.SYMBOL_COMA_DOT,
            "en_001" to Formats.SYMBOL_COMA_DOT,
            "en" to Formats.SYMBOL_COMA_DOT,
            "guz_KE" to Formats.SYMBOL_COMA_DOT,
            "zh_TW_#Hant" to Formats.SYMBOL_COMA_DOT,
            "kw_GB" to Formats.SYMBOL_COMA_DOT,
            "ug_CN" to Formats.SYMBOL_COMA_DOT,
            "es_BR" to Formats.SYMBOL_COMA_DOT,
            "zh_HK" to Formats.SYMBOL_COMA_DOT,
            "sw_KE" to Formats.SYMBOL_COMA_DOT,
            "en_SB" to Formats.SYMBOL_COMA_DOT,
            "th_TH" to Formats.SYMBOL_COMA_DOT,
            "chr_US" to Formats.SYMBOL_COMA_DOT,
            "nyn" to Formats.SYMBOL_COMA_DOT,
            "yue" to Formats.SYMBOL_COMA_DOT,
            "jmc" to Formats.SYMBOL_COMA_DOT,
            "en_MW" to Formats.SYMBOL_COMA_DOT,
            "naq_NA" to Formats.SYMBOL_COMA_DOT,
            "en_IO" to Formats.SYMBOL_COMA_DOT,
            "en_CC" to Formats.SYMBOL_COMA_DOT,
            "th" to Formats.SYMBOL_COMA_DOT,
            "dav_KE" to Formats.SYMBOL_COMA_DOT,
            "es_CU" to Formats.SYMBOL_COMA_DOT,
            "en_SC" to Formats.SYMBOL_COMA_DOT,
            "en_VI" to Formats.SYMBOL_COMA_DOT,
            "haw" to Formats.SYMBOL_COMA_DOT,
            "en_NZ" to Formats.SYMBOL_COMA_DOT,
            "mas_KE" to Formats.SYMBOL_COMA_DOT,
            "en_FJ" to Formats.SYMBOL_COMA_DOT,
            "en_BB" to Formats.SYMBOL_COMA_DOT,
            "so_SO" to Formats.SYMBOL_COMA_DOT,
            "bem" to Formats.SYMBOL_COMA_DOT,
            "en_MU" to Formats.SYMBOL_COMA_DOT,
            "en_IM" to Formats.SYMBOL_COMA_DOT,
            "en_LS" to Formats.SYMBOL_COMA_DOT,
            "en_HK" to Formats.SYMBOL_COMA_DOT,
            "en_GI" to Formats.SYMBOL_COMA_DOT,
            "en_CA" to Formats.SYMBOL_COMA_DOT,
            "gd" to Formats.SYMBOL_COMA_DOT,
            "sw_TZ" to Formats.SYMBOL_COMA_DOT,
            "so_ET" to Formats.SYMBOL_COMA_DOT,
            "cy_GB" to Formats.SYMBOL_COMA_DOT,
            "en_VG" to Formats.SYMBOL_COMA_DOT,
            "en_TC" to Formats.SYMBOL_COMA_DOT,
            "vun" to Formats.SYMBOL_COMA_DOT,
            "ki" to Formats.SYMBOL_COMA_DOT,
            "yo" to Formats.SYMBOL_COMA_DOT,
            "es_NI" to Formats.SYMBOL_COMA_DOT,
            "mas_TZ" to Formats.SYMBOL_COMA_DOT,
            "ti" to Formats.SYMBOL_COMA_DOT,
            "mfe" to Formats.SYMBOL_BLANK_BLANK_DOT,
            "mfe_MU" to Formats.SYMBOL_BLANK_BLANK_DOT,
            "kkj" to Formats.SYMBOL_BLANK_DOT_COMA,
            "sr_CS" to Formats.SYMBOL_BLANK_DOT_COMA,
            "es_CO" to Formats.SYMBOL_BLANK_DOT_COMA,
            "wo" to Formats.SYMBOL_BLANK_DOT_COMA,
            "az" to Formats.SYMBOL_BLANK_DOT_COMA,
            "az__#Cyrl" to Formats.SYMBOL_BLANK_DOT_COMA,
            "mgh" to Formats.SYMBOL_BLANK_DOT_COMA,
            "mgh_MZ" to Formats.SYMBOL_BLANK_DOT_COMA,
            "az__#Latn" to Formats.SYMBOL_BLANK_DOT_COMA,
            "pt" to Formats.SYMBOL_BLANK_DOT_COMA,
            "en_AT" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl_SR" to Formats.SYMBOL_BLANK_DOT_COMA,
            "jgo" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl_BQ" to Formats.SYMBOL_BLANK_DOT_COMA,
            "en_NL" to Formats.SYMBOL_BLANK_DOT_COMA,
            "fy_NL" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nnh" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl_NL" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl_CW" to Formats.SYMBOL_BLANK_DOT_COMA,
            "ar_DZ" to Formats.SYMBOL_BLANK_DOT_COMA,
            "rw" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl_SX" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl_AW" to Formats.SYMBOL_BLANK_DOT_COMA,
            "ar_MA" to Formats.SYMBOL_BLANK_DOT_COMA,
            "qu_BO" to Formats.SYMBOL_BLANK_DOT_COMA,
            "fur" to Formats.SYMBOL_BLANK_DOT_COMA,
            "en_CH" to Formats.SYMBOL_BLANK_DOT_COMA,
            "es_AR" to Formats.SYMBOL_BLANK_DOT_COMA,
            "pt_BR" to Formats.SYMBOL_BLANK_DOT_COMA,
            "fur_IT" to Formats.SYMBOL_BLANK_DOT_COMA,
            "fy" to Formats.SYMBOL_BLANK_DOT_COMA,
            "az_AZ_#Cyrl" to Formats.SYMBOL_BLANK_DOT_COMA,
            "es_UY" to Formats.SYMBOL_BLANK_DOT_COMA,
            "nl" to Formats.SYMBOL_BLANK_DOT_COMA,
            "az_AZ_#Latn" to Formats.SYMBOL_BLANK_DOT_COMA,
            "ms_BN" to Formats.SYMBOL_BLANK_DOT_COMA,
            "es_BO" to Formats.SYMBOL_DOT_COMA,
            "sw_CD" to Formats.SYMBOL_DOT_COMA,
            "tr_TR" to Formats.SYMBOL_DOT_COMA,
            "kl_GL" to Formats.SYMBOL_DOT_COMA,
            "kl" to Formats.SYMBOL_DOT_COMA,
            "mua" to Formats.SYMBOL_DOT_COMA,
            "in" to Formats.SYMBOL_DOT_COMA,
            "tr_CY" to Formats.SYMBOL_DOT_COMA,
            "lo" to Formats.SYMBOL_DOT_COMA,
            "es_VE" to Formats.SYMBOL_DOT_COMA,
            "tr" to Formats.SYMBOL_DOT_COMA,
            "es_EC" to Formats.SYMBOL_DOT_COMA,
            "lo_LA" to Formats.SYMBOL_DOT_COMA,
            "in_ID" to Formats.SYMBOL_DOT_COMA,
            "sg" to Formats.SYMBOL_DOT_COMA,
            "os_GE" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "nb_SJ" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "no" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "os" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "nb_NO" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "no_NO" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "eo" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "eo_001" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "de_AT" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "os_RU" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "nb" to Formats.SYMBOL_BLANK_BLANK_COMA,
            "af" to Formats.SYMBOL_BLANK_COMA,
            "en_ZA" to Formats.SYMBOL_BLANK_COMA,
            "af_ZA" to Formats.SYMBOL_BLANK_COMA,
            "es_CR" to Formats.SYMBOL_BLANK_COMA,
            "af_NA" to Formats.SYMBOL_BLANK_COMA,
            "asa_TZ" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ce" to Formats.SYMBOL_BLANK_COMA_DOT,
            "xog" to Formats.SYMBOL_BLANK_COMA_DOT,
            "asa" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ce_RU" to Formats.SYMBOL_BLANK_COMA_DOT,
            "ksb" to Formats.COMA_DOT_SYMBOL,
            "luo" to Formats.COMA_DOT_SYMBOL,
            "rwk_TZ" to Formats.COMA_DOT_SYMBOL,
            "bez" to Formats.COMA_DOT_SYMBOL,
            "ksb_TZ" to Formats.COMA_DOT_SYMBOL,
            "sbp" to Formats.COMA_DOT_SYMBOL,
            "rwk" to Formats.COMA_DOT_SYMBOL,
            "lg" to Formats.COMA_DOT_SYMBOL,
            "luo_KE" to Formats.COMA_DOT_SYMBOL,
            "bez_TZ" to Formats.COMA_DOT_SYMBOL,
            "sbp_TZ" to Formats.COMA_DOT_SYMBOL,
            "ccp" to Formats.COMA_DOT_SYMBOL,
            "ccp_BD" to Formats.COMA_DOT_SYMBOL,
            "ccp_IN" to Formats.COMA_DOT_SYMBOL,
            "khq" to Formats.BLANK_DOT_SYMBOL,
            "ses" to Formats.BLANK_DOT_SYMBOL,
            "twq" to Formats.BLANK_DOT_SYMBOL,
            "dje" to Formats.BLANK_DOT_SYMBOL,
            "hsb" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_ME" to Formats.DOT_COMA_BLANK_SYMBOL,
            "dsb_DE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "el" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_ME_#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "dsb" to Formats.DOT_COMA_BLANK_SYMBOL,
            "it_VA" to Formats.DOT_COMA_BLANK_SYMBOL,
            "es_PH" to Formats.DOT_COMA_BLANK_SYMBOL,
            "es_ES" to Formats.DOT_COMA_BLANK_SYMBOL,
            "bs_BA_#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "hsb_DE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "en_150" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ro_RO" to Formats.DOT_COMA_BLANK_SYMBOL,
            "lb_LU" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_ME_#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "eu" to Formats.DOT_COMA_BLANK_SYMBOL,
            "lb" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ln_CD" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ln" to Formats.DOT_COMA_BLANK_SYMBOL,
            "gl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr__#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "es" to Formats.DOT_COMA_BLANK_SYMBOL,
            "fr_MA" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "el_CY" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_BA_#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "bs__#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr__#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "de_IT" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_RS" to Formats.DOT_COMA_BLANK_SYMBOL,
            "bs__#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "bs_BA_#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "mk_MK" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sl_SI" to Formats.DOT_COMA_BLANK_SYMBOL,
            "it_SM" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ast" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ca_FR" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_BA_#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_XK_#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "de_BE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ca_ES" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_BA" to Formats.DOT_COMA_BLANK_SYMBOL,
            "de" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_XK_#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "fr_LU" to Formats.DOT_COMA_BLANK_SYMBOL,
            "es_EA" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ca_IT" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ca_AD" to Formats.DOT_COMA_BLANK_SYMBOL,
            "vi" to Formats.DOT_COMA_BLANK_SYMBOL,
            "de_LU" to Formats.DOT_COMA_BLANK_SYMBOL,
            "de_DE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "en_DK" to Formats.DOT_COMA_BLANK_SYMBOL,
            "it_IT" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ro" to Formats.DOT_COMA_BLANK_SYMBOL,
            "en_SI" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ln_AO" to Formats.DOT_COMA_BLANK_SYMBOL,
            "hr_HR" to Formats.DOT_COMA_BLANK_SYMBOL,
            "it" to Formats.DOT_COMA_BLANK_SYMBOL,
            "da_DK" to Formats.DOT_COMA_BLANK_SYMBOL,
            "en_BE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "fo_DK" to Formats.DOT_COMA_BLANK_SYMBOL,
            "fo_FO" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ast_ES" to Formats.DOT_COMA_BLANK_SYMBOL,
            "fo" to Formats.DOT_COMA_BLANK_SYMBOL,
            "hr" to Formats.DOT_COMA_BLANK_SYMBOL,
            "is" to Formats.DOT_COMA_BLANK_SYMBOL,
            "es_IC" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ca" to Formats.DOT_COMA_BLANK_SYMBOL,
            "mk" to Formats.DOT_COMA_BLANK_SYMBOL,
            "en_DE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "bs" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ro_MD" to Formats.DOT_COMA_BLANK_SYMBOL,
            "eu_ES" to Formats.DOT_COMA_BLANK_SYMBOL,
            "el_GR" to Formats.DOT_COMA_BLANK_SYMBOL,
            "da_GL" to Formats.DOT_COMA_BLANK_SYMBOL,
            "hr_BA" to Formats.DOT_COMA_BLANK_SYMBOL,
            "ca_ES_VALENCIA" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_RS_#Cyrl" to Formats.DOT_COMA_BLANK_SYMBOL,
            "da" to Formats.DOT_COMA_BLANK_SYMBOL,
            "gl_ES" to Formats.DOT_COMA_BLANK_SYMBOL,
            "nl_BE" to Formats.DOT_COMA_BLANK_SYMBOL,
            "sr_RS_#Latn" to Formats.DOT_COMA_BLANK_SYMBOL,
            "km" to Formats.DOT_COMA_SYMBOL,
            "seh" to Formats.DOT_COMA_SYMBOL,
            "seh_MZ" to Formats.DOT_COMA_SYMBOL,
            "rn" to Formats.DOT_COMA_SYMBOL,
            "km_KH" to Formats.DOT_COMA_SYMBOL,
            "lu_CD" to Formats.DOT_COMA_SYMBOL,
            "lu" to Formats.DOT_COMA_SYMBOL,
            "nn" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "kea" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_DZ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "lv" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sv_SE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sah" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "br" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sk" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sv" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "cs" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tzm_MA" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "smn" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tk_TM" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "se_NO" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pl_PL" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_MO" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_PM" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_MG" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "no_NO_NY" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sq_AL" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "kk" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tk" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "hy" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sv_FI" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ka" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_MF" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "kk_KZ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tt_RU" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_MC" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_MZ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ksh" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru_KZ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "et" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "be" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "dua" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_LU" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_BL" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "hu_HU" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sq_MK" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fi" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "uz" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "et_EE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "nmg" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "uz_UZ_#Latn" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_FR" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sah_RU" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ky" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sk_SK" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_CH" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_HT" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_BE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "kea_CV" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_YT" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_RE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fi_FI" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_GP" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "uk_UA" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tg" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "hu" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_CH" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "cs_CZ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru_MD" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ksf" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_TL" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sq" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tg_TJ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ksh_DE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru_RU" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "se_FI" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ff" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_CD" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_SC" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_CA" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sq_XK" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "dyo" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "yav" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "lt_LT" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "nn_NO" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_MU" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pl" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "se_SE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "se" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "be_BY" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_CV" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "uk" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tt" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru_BY" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "tzm" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_MQ" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "hy_AM" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_ST" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "lt" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "en_SE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_GF" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_AO" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru_KG" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_MR" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "en_FI" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "pt_PT" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "bas" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ru_UA" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "uz__#Latn" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "smn_FI" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "lv_LV" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ka_GE" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "fr_SY" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ky_KG" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "sv_AX" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ff_MR" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "ewo" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "br_FR" to Formats.BLANK_COMA_BLANK_SYMBOL,
            "agq" to Formats.BLANK_COMA_SYMBOL,
            "shi__#Tfng" to Formats.BLANK_COMA_SYMBOL,
            "shi__#Latn" to Formats.BLANK_COMA_SYMBOL,
            "kab_DZ" to Formats.BLANK_COMA_SYMBOL,
            "shi" to Formats.BLANK_COMA_SYMBOL,
            "zgh" to Formats.BLANK_COMA_SYMBOL,
            "zgh_MA" to Formats.BLANK_COMA_SYMBOL,
            "kab" to Formats.BLANK_COMA_SYMBOL,
            "shi_MA_#Tfng" to Formats.BLANK_COMA_SYMBOL,
            "shi_MA_#Latn" to Formats.BLANK_COMA_SYMBOL,
            "ha_NE" to Formats.SYMBOL_BLANK_COMA_WITHOUT_FRACTION,
            "mgo_CM" to Formats.SYMBOL_BLANK_COMA_WITHOUT_FRACTION,
            "nnh_CM" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "kkj_CM" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "wo_SN" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "jgo_CM" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "es_PY" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "ar_TN" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "rw_RW" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "ar_LY" to Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION,
            "sw_UG" to Formats.SYMBOL_COMA,
            "en_RW" to Formats.SYMBOL_COMA,
            "ja_JP" to Formats.SYMBOL_COMA,
            "teo_UG" to Formats.SYMBOL_COMA,
            "ko_KR" to Formats.SYMBOL_COMA,
            "en_VU" to Formats.SYMBOL_COMA,
            "en_CM" to Formats.SYMBOL_COMA,
            "nyn_UG" to Formats.SYMBOL_COMA,
            "cgg_UG" to Formats.SYMBOL_COMA,
            "en_BI" to Formats.SYMBOL_COMA,
            "so_DJ" to Formats.SYMBOL_COMA,
            "ee_TG" to Formats.SYMBOL_COMA,
            "yo_BJ" to Formats.SYMBOL_COMA,
            "ja_JP_JP_#u-ca-japanese" to Formats.SYMBOL_COMA,
            "bm_ML" to Formats.SYMBOL_COMA,
            "en_UG" to Formats.SYMBOL_COMA,
            "es_CL" to Formats.SYMBOL_DOT,
            "es_GQ" to Formats.SYMBOL_DOT,
            "mua_CM" to Formats.SYMBOL_DOT,
            "sg_CF" to Formats.SYMBOL_DOT,
            "xog_UG" to Formats.COMA_SYMBOL,
            "lg_UG" to Formats.COMA_SYMBOL,
            "ln_CF" to Formats.DOT_SYMBOL,
            "ln_CG" to Formats.DOT_SYMBOL,
            "vi_VN" to Formats.DOT_SYMBOL,
            "rn_BI" to Formats.DOT_SYMBOL,
            "is_IS" to Formats.DOT_SYMBOL,
            "fr_ML" to Formats.BLANK_SYMBOL,
            "ses_ML" to Formats.BLANK_SYMBOL,
            "dje_NE" to Formats.BLANK_SYMBOL,
            "bas_CM" to Formats.BLANK_SYMBOL,
            "agq_CM" to Formats.BLANK_SYMBOL,
            "twq_NE" to Formats.BLANK_SYMBOL,
            "nmg_CM" to Formats.BLANK_SYMBOL,
            "ksf_CM" to Formats.BLANK_SYMBOL,
            "fr_VU" to Formats.BLANK_SYMBOL,
            "fr_NE" to Formats.BLANK_SYMBOL,
            "fr_NC" to Formats.BLANK_SYMBOL,
            "fr_CM" to Formats.BLANK_SYMBOL,
            "fr_SN" to Formats.BLANK_SYMBOL,
            "ff_SN" to Formats.BLANK_SYMBOL,
            "fr_BI" to Formats.BLANK_SYMBOL,
            "dua_CM" to Formats.BLANK_SYMBOL,
            "fr_TN" to Formats.BLANK_SYMBOL,
            "fr_PF" to Formats.BLANK_SYMBOL,
            "pt_GQ" to Formats.BLANK_SYMBOL,
            "fr_BJ" to Formats.BLANK_SYMBOL,
            "dyo_SN" to Formats.BLANK_SYMBOL,
            "fr_GQ" to Formats.BLANK_SYMBOL,
            "ff_CM" to Formats.BLANK_SYMBOL,
            "fr_CI" to Formats.BLANK_SYMBOL,
            "fr_CG" to Formats.BLANK_SYMBOL,
            "fr_BF" to Formats.BLANK_SYMBOL,
            "fr_DJ" to Formats.BLANK_SYMBOL,
            "fr_CF" to Formats.BLANK_SYMBOL,
            "fr_TG" to Formats.BLANK_SYMBOL,
            "fr_GN" to Formats.BLANK_SYMBOL,
            "fr_TD" to Formats.BLANK_SYMBOL,
            "ewo_CM" to Formats.BLANK_SYMBOL,
            "pt_GW" to Formats.BLANK_SYMBOL,
            "ff_GN" to Formats.BLANK_SYMBOL,
            "fr_WF" to Formats.BLANK_SYMBOL,
            "fr_KM" to Formats.BLANK_SYMBOL,
            "khq_ML" to Formats.BLANK_SYMBOL,
            "yav_CM" to Formats.BLANK_SYMBOL,
            "fr_GA" to Formats.BLANK_SYMBOL,
            "fr_RW" to Formats.BLANK_SYMBOL
    )

    fun showFormat() : String {
//        val format = if (currencyCode == "-")
//                DecimalFormat.getInstance(Locale(languageCode, countryCode))
//        else
//                DecimalFormat.getCurrencyInstance(Locale(languageCode, countryCode))
//        return "${format.format(price.toDoubleOrNull())}"

        val result =  when(locale){
            "", "nds", "bo_CN", "qu_EC", "ta_SG", "vo", "ha_NG", "lkt_US", "ji_001", "vo_001", "ji",
            "ar_EH", "nds_DE", "mn", "ta_MY", "ta", "lag", "bo", "to", "qu", "pa_IN_#Guru", "brx",
            "ha", "bo_IN", "cu_RU", "brx_IN", "mg", "nds_NL", "mgo", "to_TO", "pa__#Guru", "ii_CN",
            "pa", "ha_GH", "ta_LK", "qu_PE", "kok_IN", "prg_001", "prg", "lag_TZ", "ur", "ur_PK",
            "mn_MN", "ii", "ta_IN", "lkt", "mg_MG", "cu", "en_IN", "kok"
            -> "${currencySymbols[currencyCode]} " + Formats.SYMBOL_BLANK_COMA_DOT.formatNumber(price.toDouble())

            "zu", "am_ET", "ti_ET", "en_NU", "zh_SG_#Hans", "en_MS", "en_GG", "en_JM", "mer", "en_ZM",
            "ml", "en_MT", "en_LR", "en_GH", "en_IL", "vai_LR_#Latn", "yo_NG", "en_PW", "fil_PH", "en_VC",
            "es_US", "en_KN", "ebu", "zh__#Hans", "es_GT", "so_KE", "kam_KE", "teo", "en_MO", "en_BZ",
            "es_DO", "en_NR", "nd", "en_MP", "en_GD", "en_BW", "en_AU", "en_CY", "kde_TZ", "ti_ER", "nus_SS",
            "nd_ZW", "en_IE", "zh_SG", "en_KI", "om_ET", "or_IN", "en_SZ", "zh", "es_PE", "saq", "en_GB",
            "zh_HK_#Hant", "es_PA", "om_KE", "en_AS", "zh_TW", "kln", "kw", "vai__#Latn", "en_JE", "en_CX",
            "luy_KE", "yue_CN_#Hans", "kn_IN", "en_SX", "ga", "en_TZ", "en_PR", "ko_KP", "sn", "rof", "en_BS",
            "gv", "gd_GB", "en_KE", "guz", "ja", "or", "te", "es_MX", "es_HN", "en_SS", "sw", "en_MG", "vai__#Vaii",
            "kn", "gu", "vun_TZ", "jmc_TZ", "en_TV", "en_PN", "en_MH", "zh__#Hant", "zh_HK_#Hans", "en_GY", "mas",
            "am", "en_NG", "ki_KE", "en_PK", "zh_CN", "en_LC", "iw", "gv_IM", "en_TT", "dav", "te_IN", "mt_MT",
            "mer_KE", "ko", "en_BM", "ak", "kde", "en_US", "gu_IN", "yue__#Hans", "en_NF", "bm", "en_GU", "en_AI", "cgg",
            "ms_MY", "en_TO", "cy", "en_PG", "en_ER", "zu_ZA", "en_PH", "zh_MO_#Hans", "en_DM", "en_CK", "ga_IE", "en_AG",
            "en_WS", "ebu_KE", "bem_ZM", "so", "en_NA", "ms", "nus", "sn_ZW", "iw_IL", "ug", "hi", "en_SL", "teo_KE",
            "zh_MO_#Hant", "en_SH", "vai", "haw_US", "en_KY", "mt", "si_LK", "kam", "en_ZW", "ee", "en_UM", "en_TK",
            "vai_LR_#Vaii", "saq_KE", "chr", "ms_SG", "yue__#Hant", "es_BZ", "luy", "rof_TZ", "en_FM", "es_PR", "naq",
            "en_SG", "ee_GH", "kln_KE", "om", "hi_IN", "en_SD", "en_MY", "es_SV", "ml_IN", "fil", "en_FK", "yue_HK_#Hant",
            "en_GM", "en_DG", "ak_GH", "zh_CN_#Hans", "es_419", "si", "en_001", "en", "guz_KE", "zh_TW_#Hant", "kw_GB",
            "ug_CN", "es_BR", "zh_HK", "sw_KE", "en_SB", "th_TH", "chr_US", "nyn", "yue", "jmc", "en_MW", "naq_NA", "en_IO",
            "en_CC", "th", "dav_KE", "es_CU", "en_SC", "en_VI", "haw", "en_NZ", "mas_KE", "en_FJ", "en_BB", "so_SO", "bem",
            "en_MU", "en_IM", "en_LS", "en_HK", "en_GI", "en_CA", "gd", "sw_TZ", "so_ET", "cy_GB", "en_VG", "en_TC", "vun",
            "ki", "yo", "es_NI", "mas_TZ", "ti"
            ->  currencySymbols[currencyCode] + Formats.SYMBOL_COMA_DOT.formatNumber(price.toDouble())

            "mfe", "mfe_MU"
            -> "${currencySymbols[currencyCode]} " + Formats.SYMBOL_BLANK_BLANK_DOT.formatNumber(price.toDouble())

            "kkj", "sr_CS", "es_CO", "wo", "az", "az__#Cyrl", "mgh", "mgh_MZ", "az__#Latn", "pt", "en_AT", "nl_SR", "jgo",
            "nl_BQ", "en_NL", "fy_NL", "nnh", "nl_NL", "nl_CW", "ar_DZ", "rw", "nl_SX", "nl_AW", "ar_MA", "qu_BO", "fur",
            "en_CH", "es_AR", "pt_BR", "fur_IT", "fy", "az_AZ_#Cyrl", "es_UY", "nl", "az_AZ_#Latn", "ms_BN"
            -> "${currencySymbols[currencyCode]} " + Formats.SYMBOL_BLANK_DOT_COMA.formatNumber(price.toDouble())

            "es_BO", "sw_CD", "tr_TR", "kl_GL", "kl", "mua", "in", "tr_CY", "lo", "es_VE", "tr", "es_EC", "lo_LA",
            "in_ID", "sg" ->  currencySymbols[currencyCode] + Formats.SYMBOL_DOT_COMA.formatNumber(price.toDouble())

            "os_GE", "nb_SJ", "no", "os", "nb_NO", "no_NO", "eo", "eo_001", "de_AT", "os_RU", "nb"
            -> "${currencySymbols[currencyCode]} " + Formats.SYMBOL_BLANK_BLANK_COMA.formatNumber(price.toDouble())

            "af", "en_ZA", "af_ZA", "es_CR", "af_NA"
            -> currencySymbols[currencyCode] + Formats.SYMBOL_BLANK_COMA.formatNumber(price.toDouble())

            "asa_TZ", "ce", "xog", "asa", "ce_RU"
            -> Formats.COMA_DOT_BLANK_SYMBOL.formatNumber(price.toDouble()) + " ${currencySymbols[currencyCode]}"

            "ksb", "luo", "rwk_TZ", "bez", "ksb_TZ", "sbp", "rwk", "lg", "luo_KE", "bez_TZ", "sbp_TZ",
            "ccp", "ccp_BD", "ccp_IN"
            -> Formats.COMA_DOT_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            "khq", "ses", "twq", "dje"
            -> Formats.BLANK_DOT_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            "hsb", "sr_ME", "dsb_DE", "el", "sr_ME_#Cyrl", "dsb", "it_VA", "es_PH", "es_ES", "bs_BA_#Latn", "hsb_DE",
            "en_150", "ro_RO", "lb_LU", "sr_ME_#Latn", "eu", "lb", "ln_CD", "ln", "gl", "sr__#Cyrl", "es", "fr_MA",
            "sl", "el_CY", "sr_BA_#Cyrl", "bs__#Cyrl", "sr__#Latn", "de_IT", "sr_RS", "bs__#Latn", "bs_BA_#Cyrl",
            "mk_MK", "sl_SI", "it_SM", "ast", "ca_FR", "sr_BA_#Latn", "sr_XK_#Cyrl", "de_BE", "ca_ES", "sr_BA", "de",
            "sr_XK_#Latn", "fr_LU", "es_EA", "ca_IT", "ca_AD", "vi", "de_LU", "de_DE", "en_DK", "it_IT", "ro", "en_SI",
            "ln_AO", "hr_HR", "it", "da_DK", "en_BE", "fo_DK", "fo_FO", "ast_ES", "fo", "hr", "is", "es_IC", "ca", "mk",
            "en_DE", "bs", "ro_MD", "eu_ES", "el_GR", "da_GL", "hr_BA", "ca_ES_VALENCIA", "sr", "sr_RS_#Cyrl", "da",
            "gl_ES", "nl_BE", "sr_RS_#Latn"
            -> Formats.DOT_COMA_BLANK_SYMBOL.formatNumber(price.toDouble()) + " ${currencySymbols[currencyCode]}"

            "km", "seh", "seh_MZ", "rn", "km_KH", "lu_CD", "lu"
            -> Formats.DOT_COMA_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            "nn", "kea", "fr_DZ", "lv", "sv_SE", "sah", "br", "sk", "sv", "cs", "tzm_MA", "smn", "tk_TM", "se_NO",
            "pl_PL", "pt_MO", "fr_PM", "fr_MG", "no_NO_NY", "sq_AL", "ru", "kk", "tk", "hy", "sv_FI", "ka", "fr_MF",
            "kk_KZ", "tt_RU", "fr_MC", "pt_MZ", "ksh", "ru_KZ", "et", "be", "dua", "pt_LU", "fr_BL", "hu_HU", "sq_MK",
            "fi", "uz", "et_EE", "nmg", "uz_UZ_#Latn", "fr_FR", "sah_RU", "ky", "sk_SK", "pt_CH", "fr_HT", "fr_BE",
            "kea_CV", "fr_YT", "fr_RE", "fi_FI", "fr_GP", "uk_UA", "tg", "hu", "fr_CH", "cs_CZ", "ru_MD", "ksf",
            "pt_TL", "sq", "fr", "tg_TJ", "ksh_DE", "ru_RU", "se_FI", "ff", "fr_CD", "fr_SC", "fr_CA", "sq_XK", "dyo",
            "yav", "lt_LT", "nn_NO", "fr_MU", "pl", "se_SE", "se", "be_BY", "pt_CV", "uk", "tt", "ru_BY", "tzm",
            "fr_MQ", "hy_AM", "pt_ST", "lt", "en_SE", "fr_GF", "pt_AO", "ru_KG", "fr_MR", "en_FI", "pt_PT", "bas",
            "ru_UA", "uz__#Latn", "smn_FI", "lv_LV", "ka_GE", "fr_SY", "ky_KG", "sv_AX", "ff_MR", "ewo", "br_FR"
            -> Formats.BLANK_COMA_BLANK_SYMBOL.formatNumber(price.toDouble()) + " ${currencySymbols[currencyCode]}"

            "agq", "shi__#Tfng", "shi__#Latn", "kab_DZ", "shi", "zgh", "zgh_MA", "kab", "shi_MA_#Tfng",
            "shi_MA_#Latn" -> Formats.BLANK_COMA_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            "ha_NE", "mgo_CM"
            -> "${currencySymbols[currencyCode]} " + Formats.SYMBOL_BLANK_COMA_WITHOUT_FRACTION.formatNumber(price.toDouble())

            "nnh_CM", "kkj_CM", "wo_SN", "jgo_CM", "es_PY", "ar_TN", "rw_RW", "ar_LY"
            -> "${currencySymbols[currencyCode]} " + Formats.SYMBOL_BLANK_DOT_WITHOUT_FRACTION.formatNumber(price.toDouble())

            "sw_UG", "en_RW", "ja_JP", "teo_UG", "ko_KR", "en_VU", "en_CM", "nyn_UG", "cgg_UG", "en_BI", "so_DJ",
            "ee_TG", "yo_BJ", "ja_JP_JP_#u-ca-japanese", "bm_ML", "en_UG"
            -> currencySymbols[currencyCode] + Formats.SYMBOL_COMA.formatNumber(price.toDouble())

            "es_CL", "es_GQ", "mua_CM", "sg_CF" -> currencySymbols[currencyCode] + Formats.SYMBOL_DOT.formatNumber(price.toDouble())

            "xog_UG", "lg_UG" -> Formats.COMA_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            "ln_CF", "ln_CG", "vi_VN", "rn_BI", "is_IS"
            -> Formats.DOT_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            "fr_ML", "ses_ML", "dje_NE", "bas_CM", "agq_CM", "twq_NE", "nmg_CM", "ksf_CM", "fr_VU", "fr_NE", "fr_NC",
            "fr_CM", "fr_SN", "ff_SN", "fr_BI", "dua_CM", "fr_TN", "fr_PF", "pt_GQ", "fr_BJ", "dyo_SN", "fr_GQ",
            "ff_CM", "fr_CI", "fr_CG", "fr_BF", "fr_DJ", "fr_CF", "fr_TG", "fr_GN", "fr_TD", "ewo_CM", "pt_GW",
            "ff_GN", "fr_WF", "fr_KM", "khq_ML", "yav_CM", "fr_GA", "fr_RW"
            -> Formats.BLANK_SYMBOL.formatNumber(price.toDouble()) + currencySymbols[currencyCode]

            else -> ""
        }

        return if (price.toDouble() < 0)
            "-$result"
        else
            result
    }
}